[project]
name = "gseekbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.28.2",
    "aiogram-i18n[fluent-compile]>=1.5",
    "aiohttp>=3.13.5",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "dishka>=1.10.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "sqlalchemy>=2.0.50",
]

[project.optional-dependencies]
dev = [
    "FTL-Extract==0.9.0a10",
    "pre-commit==4.3.0",
]
lint = [
    "ruff==0.14.0",
    "mypy==1.18.2",
    "types-pytz==2025.2.0.20250809",
]

[tool.ruff]
line-length = 99
src = ["app"]
exclude = [
    ".git",
    "build",
    "dist",
    "venv",
    ".venv",
    "*.egg-info",
    "app/i18n/locales",
]

[tool.ruff.lint]
select = [
    "W",     # pycodestyle warnings
    "N",     # pep8-naming
    "PTH",   # flake8-use-pathlib
    "G",     # flake8-logging-format
    "ANN",   # flake8-annotations
    "TCH",   # flake8-type-checking
    "PYI",   # flake8-pyi
    "FA",    # flake8-future-annotations
    "A",    # flake8-builtins — conflicts with built-in names
    "B",    # flake8-bugbear — common bugs
    "C4",   # flake8-comprehensions — unnecessary list/dict comprehensions
    "DTZ",  # flake8-datetimez — datetime without timezone
    "E",    # pycodestyle errors
    "F",    # pyflakes — unused imports, variables
    "I",    # isort — import order
    "PERF", # perflint — performance issues
    "PL",   # pylint
    "Q",    # flake8-quotes
    "RET",  # flake8-return — unnecessary return
    "SIM",  # flake8-simplify — code simplification
    "T10",  # flake8-debugger — left-over breakpoint()
    "T20",  # flake8-print — left-over print()
    "UP",   # pyupgrade — older Python syntax
]
ignore = [
    "A002",    # builtin-argument-shadowing
    "A005",    # stdlib-module-shadowing
    "B008",    # function-call-in-default-argument
    "PLC0415", # import-outside-top-level
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "PLR6301", # no-self-use
    "ANN401",
    "ANN101",
    "ANN102",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
plugins = ["pydantic.mypy"]
python_version = "3.13"
show_error_codes = true
show_error_context = true
pretty = true
ignore_missing_imports = false
warn_unused_configs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
namespace_packages = true
show_absolute_path = true
disallow_any_explicit = true
disallow_subclassing_any = true
warn_no_return = true
extra_checks = true

[tool.pyright]
venvPath = "."
venv = ".venv"
