name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          if [ ! -d /project/prod/gseekbot/.git ]; then
            if [ -d /project/prod/gseekbot ]; then
              rm -rf /project/prod/gseekbot
            fi
            git clone https://github.com/yourusername/yourrepo.git /project/prod/gseekbot
          else
            cd /project/prod/gseekbot
            git pull origin main
          fi
          cd /project/prod/gseekbot
          echo "${{ secrets.ENV_CONTENT }}" > .env
          docker compose down
          docker compose up -d --build
